name: Deploy on EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: appleboy ssh
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.PROD_HOST }} //add ip of the prod host
          username: ubuntu
          key: ${{ secrets.SSH_KEY }} //private ssh key or pem file
          port: 22
          scripts: |
                export NVM_DIR="$HOME/.nvm"
                source "$NVM_DIR/nvm.sh"

                cd second-brain
                git pull origin main
                echo "VITE_API=http://${{ secrets.PROD_HOST }}" >> Frontend/.env
                echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> Backend/.env
                echo "PORT=${{ secrets.BACKEND_PORT }}" >> Backend/.env
                echo "JWT_SECRET=sdfkjhsdfhoiwejfsdjflk" >> Backend/.env
                cd Frontend
                npm install
                npm run build
                cd ../Backend
                npm install
                npm run build
                pm2 restart all
                